name: Windows Test

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Show Windows information
        run: |
          systeminfo
          echo "GitHub Windows runner is working."
